

//AUTHENTICATION
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const LOGOUT = 'LOGOUT';

 
//CARGAR DATOS DE USUARIO

export const CARGAR_DATOS_USUARIO_REQUEST = 'CARGAR_DATOS_USUARIO_REQUEST';
export const CARGAR_DATOS_USUARIO_EXITOSO = 'CARGAR_DATOS_USUARIO_EXITOSO';
export const CARGAR_DATOS_USUARIO_FALLIDO = 'CARGAR_DATOS_USUARIO_FALLIDO';


//MATERIAS

export const GET_MATERIAS_REQUEST = 'GET_MATERIAS_REQUEST';
export const GET_MATERIAS_EXITOSO = 'GET_MATERIAS_EXITOSO';
export const GET_MATERIAS_FALLIDO = 'GET_MATERIAS_FALLIDO';

export const POST_MATERIA_REQUEST = 'POST_MATERIA_REQUEST';
export const POST_MATERIA_EXITOSO = 'POST_MATERIA_EXITOSO';
export const POST_MATERIA_FALLIDO = 'POST_MATERIA_FALLIDO';


export const PUT_MATERIA_REQUEST = 'PUT_MATERIA_REQUEST';
export const PUT_MATERIA_EXITOSO = 'PUT_MATERIA_EXITOSO';
export const PUT_MATERIA_FALLIDO = 'PUT_MATERIA_FALLIDO';


export const ACTIVAR_MATERIA_REQUEST = 'ACTIVAR_MATERIA_REQUEST';
export const ACTIVAR_MATERIA_EXITOSO = 'ACTIVAR_MATERIA_EXITOSO';
export const ACTIVAR_MATERIA_FALLIDO = 'ACTIVAR_MATERIA_FALLIDO';

export const DESACTIVAR_MATERIA_REQUEST = 'DESACTIVAR_MATERIA_REQUEST';
export const DESACTIVAR_MATERIA_EXITOSO = 'DESACTIVAR_MATERIA_EXITOSO';
export const DESACTIVAR_MATERIA_FALLIDO = 'DESACTIVAR_MATERIA_FALLIDO';

export const ELIMINAR_STATE_MATERIAS = 'ELIMINAR_STATE_MATERIAS'
